### PR TITLE
Rampage added

### PR DESCRIPTION
**Pull request by filen1**
@mgsweet 
It's all there so you can just carry it over. My other patterns might not be for everyone so maybe not carry those over (r301 only good 2x+ etc..) the rampage pattern is much better than the one I posted in the issue. 

Also I forgot to mention I still don't truly understand how it started to work this time. I just tried a bunch of different combinations with the correct ffffff values being true and a random one being false, can you clarify?

### CODE REVIEW

**Comment by filen1** [comment]
Actually isn't working 100% of the time. I do not know why...

**Comment by filen1** [comment]
global RAMPAGE_PIXELS := [1709, 988, true, 1650, 992, false, 1630, 982, true]


This worked. but so did the other one at first, please test.

**Comment by mgsweet** [comment]
I think this pull request has many problems. It rollback my code, I will try to fix it

**Comment by filen1** [comment]
@mgsweet idk how to just pull request specific things. Just wanted to give you rampage code so you can implement. sorry if I used it wrong I dont know how it works.

**Comment by mgsweet** [comment]
@filen1 thanks a lot. I have copy and paste your work to the main branch. There are some conflict issue and unknown rollback issues in this pull request. Take a look at the latest update.

things you need to know:
i have test all those pattern, still using the previous pattern for r301 and prowler. Also the modifier is still 2.5/sens.

**Comment by filen1** [comment]
> @filen1 thanks a lot. I have copy and paste your work to the main branch. There are some conflict issue and unknown rollback issues in this pull request. Take a look at the latest update.
> 
> things you need to know:
> i have test all those pattern, still using the previous pattern for r301 and prowler. Also the modifier is still 2.5/sens.

Yes those patterns are for 2.5 sens (in game and in settings ini) with 3.4 modifier as is in the ahk file. The r301 is terrible with 1x scope but really good with 4x (its for arenas).

**Comment by mgsweet** [comment]
@filen1 I did try 3.4 in code. but it sometime compensates too much. I prefer not that accurate instead of over compensation

**Pull request closed without merging**
