### PR TITLE
Season 17 Patch

### PR DESCRIPTION
**Pull request by Eternal-Walnut**

### CODE REVIEW

**Comment by hitch3ns** [comment]
r99 tested so perfect

**Comment by hitch3ns** [comment]
LStar - perfect

**Review by mgsweet — APPROVED** [review]
Thanks for updating the script. I haven't done any tests yet. Will do some tests and release your work this weekend :)

**Comment by Eternal-Walnut** [comment]
> Thanks for updating the script. I haven't done any tests yet. Will do some tests and release your work this weekend :)

do one's bit :)

**Pull request merged**
