### PR TITLE
Update gold optics

### PR DESCRIPTION
**Pull request by Eternal-Walnut**

### CODE REVIEW

**Comment by hitch3ns** [comment]
i never used gold optic cause i though it may lead to ban

**Comment by Eternal-Walnut** [comment]
I don't use this, I just update it haha

**Comment by mgsweet** [comment]
What is this change about?

**Comment by Eternal-Walnut** [comment]
> What is this change about? Descriptions for this PR is needed.

After this modification, gold options will support all sniper guns, not just wingman

**Review by mgsweet — APPROVED** [review]

**Comment by DarkShori** [comment]
> > What is this change about? Descriptions for this PR is needed.
> 
> After this modification, gold options will support all sniper guns, not just wingman Because all sniper guns can be equipped with gold optics sight

How do i used this gold optic... i enable it and everything.. ahk no recoil is working fine with guns but this one doesn't seem to do anything.. do i need to press anything its not auto-aiming when using gold optics even with wingman..

**Comment by Eternal-Walnut** [comment]
> > > What is this change about? Descriptions for this PR is needed.
> > 
> > 
> > After this modification, gold options will support all sniper guns, not just wingman Because all sniper guns can be equipped with gold optics sight
> 
> How do i used this gold optic... i enable it and everything.. ahk no recoil is working fine with guns but this one doesn't seem to do anything.. do i need to press anything its not auto-aiming when using gold optics even with wingman..

Hey, honestly, i don't know. because I haven't use this feature :)

**Pull request merged**
